// Copyright 2015 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Reconstructed from com.google.testing.platform:core-proto:0.0.9-alpha04.

syntax = "proto3";

package google.testing.platform.proto.api.config;

import "proto/api/config/adb_config.proto";
import "proto/api/config/runtime.proto";

option java_package = "com.google.testing.platform.proto.api.config";
option java_outer_classname = "LocalAndroidDeviceProviderProto";

enum DeviceType {
  UNKNOWN_DEVICE = 0;
  SIMULATED = 1;
  VIRTUAL = 2;
  PHYSICAL = 3;
}

message LocalAndroidDeviceProvider {
  string host = 1;
  string serial = 2;
  int32 adb_server_port = 3;
  int32 console_port = 4;
  int32 adb_port = 5;
  DeviceType device_type = 6;
  AndroidInstrumentationRuntime android_instrumentation_runtime = 7;
  AdbConfig adb_config = 8;
  bool enable_device_state_monitoring = 9;
}
